#!/bin/sh
export PV_PLUGIN_PATH="/usr/lib/x86_64-linux-gnu/paraview-5.11/plugins"
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions

log_output(){
  if [ $1 != 0 ]; then
  echo "$2">"./log.txt";
  exit  1;
fi
}
out=$(cleanCase 2>&1 >/dev/null)
log_output $? "$out"

out=$(blockMesh 2>&1 >/dev/null)
log_output $? "$out"

out=$(surfaceFeatureExtract 2>&1 >/dev/null)
log_output $? "$out"

out=$(snappyHexMesh -overwrite 2>&1 >/dev/null)
log_output $? "$out"

mv 0/U U
mv 0/p p

out=$(stitchMesh mesh mesh_slave -perfect -overwrite 2>&1 >/dev/null)
log_output $? "$out"

out=$(createPatch -overwrite 2>&1 >/dev/null)
log_output $? "$out"

mv U 0/U
mv p 0/p
rm -f 0/meshPhi

out=$(splitMeshRegions -cellZones -overwrite -detectOnly 2>&1 >/dev/null)
log_output $? "$out"

start=$(date +%s%N)

out=$(decomposePar 2>&1 >/dev/null)
log_output $? "$out"

out=$(mpirun -np $n_proc $(getApplication) -parallel 2>&1 >/dev/null)
log_output $? "$out"

out=$(reconstructPar 2>&1 >/dev/null)
log_output $? "$out"

end=$(date +%s%N)
echo "$(($end-$start))" > ./timing.txt
