#!/bin/sh
export PV_PLUGIN_PATH="/usr/lib/x86_64-linux-gnu/paraview-5.11/plugins"
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions

cleanCase
extrudeMesh
splitMeshRegions -cellZonesOnly -overwrite -detectOnly

start=$(date +%s%N)
$(getApplication)
end=end=$(date +%s%N)
echo "$(($end-$start))" > ./timing.txt